// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "Xr!pVC?XDgle;}EBTe5{":
            case "maguinho0":return img`
........................
........................
........................
.....ffffff.............
....faaaaaaff...........
...faaaaaaaaaff.........
...faafaaaaaaaaf........
....ff.faaaaaaaaf.......
.......faaaaaaaaf.......
....fffbbbbbbbbbbfff....
...faaaaaaaaaaaaaaaaf...
...faaaaaaaaaaaaaaaaf...
....fffddffffd66dfff....
......fddffffd66df......
......fddff1111ddf......
......fdfb111111bf......
.....fbfdd11c111dbf.....
....fdbdddbbbbbbdbdf....
...fddbdddbbbbbbdbddf...
...fddfdddbbbbbbdfddf...
....fffddddbbbbddfff....
.......fbbbffbbbf.......
.......fdddffdddf.......
........fddffddf........
`;
            case "{nyh}^a^Q,IJSM,G+":
            case "maguinho1":return img`
........................
........................
.....ffffff.............
....faaaaaaff...........
...faaaaaaaaaff.........
...faafaaaaaaaaf........
....ff.faaaaaaaaf.......
.......faaaaaaaaf.......
....fffbbbbbbbbbbfff....
...faaaaaaaaaaaaaaaaf...
...faaaaaaaaaaaaaaaaf...
....fffddffffd66dfff....
......fddffffd66df......
......fddff1111ddf......
......fdfb111111bf......
.....fbfdd11c111dbf.....
....fdbdddbbbbbbdbdf....
...fddbdddbbbbbbdbddf...
...fddfdddbbbbbbdfddf...
....fffddddbbbbddfff....
......fbddddddddbf......
......fdbffffffbdf......
......fddf....fddf......
.......ff......ff.......
`;
            case "!?FeH`azF,idoiJBc(bh":
            case "maguinho2":return img`
........................
.....ffffff.............
....faaaaaaff...........
...faaaaaaaaaff.........
...faafaaaaaaaaf........
....ff.faaaaaaaaf.......
.......faaaaaaaaf.......
....fffbbbbbbbbbbfff....
...faaaaaaaaaaaaaaaaf...
...faaaaaaaaaaaaaaaaf...
....fffddffffd66dfff....
......fddffffd66df......
......fddff1111ddf......
......fdfb111111bf......
......ffdd11c111df......
.....fbdddbbbbbbdbf.....
....fdbdddbbbbbbdbdf....
...fddbdddbbbbbbdbddf...
...fddfddddbbbbddfddf...
....fffbddddddddbfff....
.....fddbffffffbddf.....
.....fddf......fddf.....
......ff........ff......
........................
`;
            case "OH=Hq`rC*U1!Q(GQj~jP":
            case "maguinho3":return img`
........................
........................
.....ffffff.............
....faaaaaaff...........
...faaaaaaaaaff.........
...faafaaaaaaaaf........
....ff.faaaaaaaaf.......
.......faaaaaaaaf.......
....fffbbbbbbbbbbfff....
...faaaaaaaaaaaaaaaaf...
...faaaaaaaaaaaaaaaaf...
....fffddffffd66dfff....
......fddffffd66df......
......fddff1111ddf......
......fdfb111111bf......
.....fbfdd11c111dbf.....
....fdbdddbbbbbbdbdf....
...fddbdddbbbbbbdbddf...
...fddfdddbbbbbbdfddf...
....fffddddbbbbddfff....
......fbddddddddbf......
......fdbffffffbdf......
......fddf....fddf......
.......ff......ff.......
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
